Repository woorifisa-projects/i-was-a-car-back, pull requests merged in 2023-08, with the labels that each got.

#11 엔티티 매핑
  .gitignore
  .gradle/8.2.1/checksums/checksums.lock
  .gradle/8.2.1/checksums/md5-checksums.bin
  .gradle/8.2.1/checksums/sha1-checksums.bin
  .gradle/8.2.1/dependencies-accessors/dependencies-accessors.lock
  .gradle/8.2.1/dependencies-accessors/gc.properties
  .gradle/8.2.1/executionHistory/executionHistory.bin
  .gradle/8.2.1/executionHistory/executionHistory.lock
  .gradle/8.2.1/fileChanges/last-build.bin
  .gradle/8.2.1/fileHashes/fileHashes.bin
  .gradle/8.2.1/fileHashes/fileHashes.lock
  .gradle/8.2.1/fileHashes/resourceHashesCache.bin
  .gradle/8.2.1/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .gradle/vcs-1/gc.properties
  src/main/java/xyz/iwasacar/api/domain/agreementhistories/entity/DocumentConsentHistory.java
  src/main/java/xyz/iwasacar/api/domain/banks/entity/Bank.java
  src/main/java/xyz/iwasacar/api/domain/brands/entity/Brand.java
  src/main/java/xyz/iwasacar/api/domain/caroptions/entity/CarOption.java
  src/main/java/xyz/iwasacar/api/domain/caroptions/entity/ProductOption.java
  src/main/java/xyz/iwasacar/api/domain/cartypes/entity/CarType.java
  src/main/java/xyz/iwasacar/api/domain/colors/entity/Color.java
  src/main/java/xyz/iwasacar/api/domain/common/constant/EntityStatus.java
  src/main/java/xyz/iwasacar/api/domain/documentitems/entity/DocumentItem.java
  src/main/java/xyz/iwasacar/api/domain/documents/entity/Document.java
  src/main/java/xyz/iwasacar/api/domain/histories/entity/PurchaseHistory.java
  src/main/java/xyz/iwasacar/api/domain/histories/entity/SaleHistory.java
  src/main/java/xyz/iwasacar/api/domain/insurances/entity/Insurance.java
  src/main/java/xyz/iwasacar/api/domain/labels/entity/Label.java
  src/main/java/xyz/iwasacar/api/domain/labels/entity/LabelName.java
  src/main/java/xyz/iwasacar/api/domain/loans/entity/Loan.java
  src/main/java/xyz/iwasacar/api/domain/logs/entity/Log.java
  src/main/java/xyz/iwasacar/api/domain/members/entity/Gender.java
  src/main/java/xyz/iwasacar/api/domain/members/entity/Member.java
  src/main/java/xyz/iwasacar/api/domain/products/entity/Product.java
  src/main/java/xyz/iwasacar/api/domain/resources/entity/ProductImage.java
  src/main/java/xyz/iwasacar/api/domain/resources/entity/Resource.java
  src/main/java/xyz/iwasacar/api/domain/roles/entity/MemberRole.java
  src/main/java/xyz/iwasacar/api/domain/roles/entity/Role.java
  src/main/java/xyz/iwasacar/api/domain/roles/entity/RoleName.java
Labels: feature

#13 chore: 프로젝트 기본 세팅 [#12]
  .gitignore
  build.gradle
  src/main/java/xyz/iwasacar/api/common/component/BcryptPasswordEncoder.java
  src/main/java/xyz/iwasacar/api/common/component/PasswordEncoder.java
  src/main/java/xyz/iwasacar/api/common/config/AwsS3Config.java
  src/main/java/xyz/iwasacar/api/common/config/P6spyLogMessageFormatConfiguration.java
  src/main/java/xyz/iwasacar/api/common/config/P6spySqlFormatConfiguration.java
  src/main/java/xyz/iwasacar/api/common/config/QueryDslConfig.java
  src/main/java/xyz/iwasacar/api/common/config/SecurityConfig.java
  src/main/java/xyz/iwasacar/api/common/dto/response/CommonResponse.java
  src/main/java/xyz/iwasacar/api/common/dto/response/ErrorResponse.java
  src/main/java/xyz/iwasacar/api/common/dto/response/PageResponse.java
  src/main/java/xyz/iwasacar/api/common/exception/advice/GlobalRestControllerAdvice.java
  src/main/java/xyz/iwasacar/api/common/exception/base/BaseAbstractException.java
  src/main/java/xyz/iwasacar/api/common/exception/base/ExceptionStatus.java
  src/main/java/xyz/iwasacar/api/domain/brands/entity/Brand.java
  src/main/java/xyz/iwasacar/api/domain/caroptions/entity/ProductOption.java
  src/main/java/xyz/iwasacar/api/domain/cartypes/entity/CarType.java
  src/main/java/xyz/iwasacar/api/domain/documentitems/entity/DocumentItem.java
  src/main/java/xyz/iwasacar/api/domain/histories/entity/PurchaseHistory.java
  src/main/java/xyz/iwasacar/api/domain/histories/entity/SaleHistory.java
  src/main/java/xyz/iwasacar/api/domain/loans/entity/Loan.java
  src/main/java/xyz/iwasacar/api/domain/logs/entity/Log.java
  src/main/java/xyz/iwasacar/api/domain/members/controller/MemberController.java
  src/main/java/xyz/iwasacar/api/domain/members/entity/Member.java
  src/main/java/xyz/iwasacar/api/domain/products/entity/Product.java
  src/main/java/xyz/iwasacar/api/domain/resources/entity/ProductImage.java
  src/main/java/xyz/iwasacar/api/domain/roles/entity/MemberRole.java
  src/main/java/xyz/iwasacar/api/domain/roles/entity/Role.java
Labels: feature

#16 feat: 상품 상세 조회 API 개발 [#3]
  build.gradle
  src/main/java/xyz/iwasacar/api/common/dto/response/CommonResponse.java
  src/main/java/xyz/iwasacar/api/common/exception/base/ExceptionStatus.java
  src/main/java/xyz/iwasacar/api/domain/caroptions/repository/CarOptionRepository.java
  src/main/java/xyz/iwasacar/api/domain/caroptions/repository/CarOptionRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/caroptions/repository/CarOptionRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/products/controller/ProductController.java
  src/main/java/xyz/iwasacar/api/domain/products/dto/response/ProductDetailResponse.java
  src/main/java/xyz/iwasacar/api/domain/products/entity/Product.java
  src/main/java/xyz/iwasacar/api/domain/products/exception/ProductNotFound.java
  src/main/java/xyz/iwasacar/api/domain/products/repository/ProductRepository.java
  src/main/java/xyz/iwasacar/api/domain/products/repository/ProductRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/products/repository/ProductRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/products/service/DefaultProductService.java
  src/main/java/xyz/iwasacar/api/domain/products/service/ProductService.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepository.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
Labels: feature

#14 title: [refactor] status있는 entity에 updatedAt, deletedAt추가
  src/main/java/xyz/iwasacar/api/domain/consenthistories/entity/DocumentConsentHistory.java
  src/main/java/xyz/iwasacar/api/domain/documentitems/entity/DocumentItem.java
  src/main/java/xyz/iwasacar/api/domain/documents/entity/Document.java
  src/main/java/xyz/iwasacar/api/domain/histories/entity/PurchaseHistory.java
  src/main/java/xyz/iwasacar/api/domain/histories/entity/SaleHistory.java
  src/main/java/xyz/iwasacar/api/domain/members/entity/Member.java
  src/main/java/xyz/iwasacar/api/domain/products/entity/Product.java
  src/main/java/xyz/iwasacar/api/domain/resources/entity/Resource.java
Labels: refactor

#17 Feature/docker
  Dockerfile
  build.gradle
  src/main/resources/.gitkeep
Labels: refactor

#18 develop to main
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/xyz/iwasacar/api/common/component/BcryptPasswordEncoder.java
  src/main/java/xyz/iwasacar/api/common/component/PasswordEncoder.java
  src/main/java/xyz/iwasacar/api/common/config/AwsS3Config.java
  src/main/java/xyz/iwasacar/api/common/config/P6spyLogMessageFormatConfiguration.java
  src/main/java/xyz/iwasacar/api/common/config/P6spySqlFormatConfiguration.java
  src/main/java/xyz/iwasacar/api/common/config/QueryDslConfig.java
  src/main/java/xyz/iwasacar/api/common/config/SecurityConfig.java
  src/main/java/xyz/iwasacar/api/common/dto/response/CommonResponse.java
  src/main/java/xyz/iwasacar/api/common/dto/response/ErrorResponse.java
  src/main/java/xyz/iwasacar/api/common/dto/response/PageResponse.java
  src/main/java/xyz/iwasacar/api/common/exception/advice/GlobalRestControllerAdvice.java
  src/main/java/xyz/iwasacar/api/common/exception/base/BaseAbstractException.java
  src/main/java/xyz/iwasacar/api/common/exception/base/ExceptionStatus.java
  src/main/java/xyz/iwasacar/api/domain/brands/entity/Brand.java
  src/main/java/xyz/iwasacar/api/domain/caroptions/entity/ProductOption.java
  src/main/java/xyz/iwasacar/api/domain/caroptions/repository/CarOptionRepository.java
  src/main/java/xyz/iwasacar/api/domain/caroptions/repository/CarOptionRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/caroptions/repository/CarOptionRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/cartypes/entity/CarType.java
  src/main/java/xyz/iwasacar/api/domain/consenthistories/entity/DocumentConsentHistory.java
  src/main/java/xyz/iwasacar/api/domain/documentitems/entity/DocumentItem.java
  src/main/java/xyz/iwasacar/api/domain/documents/entity/Document.java
  src/main/java/xyz/iwasacar/api/domain/histories/entity/PurchaseHistory.java
  src/main/java/xyz/iwasacar/api/domain/histories/entity/SaleHistory.java
  src/main/java/xyz/iwasacar/api/domain/loans/entity/Loan.java
  src/main/java/xyz/iwasacar/api/domain/logs/entity/Log.java
  src/main/java/xyz/iwasacar/api/domain/members/controller/MemberController.java
  src/main/java/xyz/iwasacar/api/domain/members/entity/Member.java
  src/main/java/xyz/iwasacar/api/domain/products/controller/ProductController.java
  src/main/java/xyz/iwasacar/api/domain/products/dto/response/ProductDetailResponse.java
  src/main/java/xyz/iwasacar/api/domain/products/entity/Product.java
  src/main/java/xyz/iwasacar/api/domain/products/exception/ProductNotFound.java
  src/main/java/xyz/iwasacar/api/domain/products/repository/ProductRepository.java
  src/main/java/xyz/iwasacar/api/domain/products/repository/ProductRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/products/repository/ProductRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/products/service/DefaultProductService.java
  src/main/java/xyz/iwasacar/api/domain/products/service/ProductService.java
  src/main/java/xyz/iwasacar/api/domain/resources/entity/ProductImage.java
  src/main/java/xyz/iwasacar/api/domain/resources/entity/Resource.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepository.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/roles/entity/MemberRole.java
  src/main/java/xyz/iwasacar/api/domain/roles/entity/Role.java
  src/main/resources/.gitkeep
Labels: feature

#22 [refactor] 문서동의내역 엔티티 수정
  src/main/java/xyz/iwasacar/api/domain/consenthistories/entity/DocumentConsentHistory.java
Labels: refactor

#21 [feat] DB 이중화 설정
  src/main/java/xyz/iwasacar/api/common/config/database/DataSourceConfig.java
  src/main/java/xyz/iwasacar/api/common/config/database/DataSourceType.java
  src/main/java/xyz/iwasacar/api/common/config/database/DbConstUtil.java
  src/main/java/xyz/iwasacar/api/common/config/database/RoutingDataSource.java
  src/main/java/xyz/iwasacar/api/common/config/database/RoutingDataSourceConfig.java
Labels: feature

#19 [feat] 상품목록 조회 API 개발
  src/main/java/xyz/iwasacar/api/domain/brands/entity/Brand.java
  src/main/java/xyz/iwasacar/api/domain/common/constant/EntityStatus.java
  src/main/java/xyz/iwasacar/api/domain/labels/entity/LabelName.java
  src/main/java/xyz/iwasacar/api/domain/products/controller/ProductController.java
  src/main/java/xyz/iwasacar/api/domain/products/dto/response/ProductResponse.java
  src/main/java/xyz/iwasacar/api/domain/products/service/DefaultProductService.java
  src/main/java/xyz/iwasacar/api/domain/products/service/ProductService.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
Labels: feature

#23 [refactor] 상품 상세 수정
  src/main/java/xyz/iwasacar/api/domain/common/constant/EntityStatus.java
  src/main/java/xyz/iwasacar/api/domain/labels/entity/LabelName.java
  src/main/java/xyz/iwasacar/api/domain/products/repository/ProductRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
Labels: refactor

#24 [feat] 특정 대출 상품 조회 API 개발
  src/main/java/xyz/iwasacar/api/common/config/P6spyLogMessageFormatConfiguration.java
  src/main/java/xyz/iwasacar/api/domain/loans/controller/LoanController.java
  src/main/java/xyz/iwasacar/api/domain/loans/dto/response/LoanResponse.java
  src/main/java/xyz/iwasacar/api/domain/loans/entity/Loan.java
  src/main/java/xyz/iwasacar/api/domain/loans/repository/LoanRepository.java
  src/main/java/xyz/iwasacar/api/domain/loans/repository/LoanRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/loans/repository/LoanRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/loans/service/DefaultLoanService.java
  src/main/java/xyz/iwasacar/api/domain/loans/service/LoanService.java
Labels: feature

#25 [feat] 보험 상품 조회
  src/main/java/xyz/iwasacar/api/domain/insurances/controller/InsuranceController.java
  src/main/java/xyz/iwasacar/api/domain/insurances/dto/response/InsuranceResponse.java
  src/main/java/xyz/iwasacar/api/domain/insurances/repository/InsuranceRepository.java
  src/main/java/xyz/iwasacar/api/domain/insurances/service/DefaultInsuranceService.java
  src/main/java/xyz/iwasacar/api/domain/insurances/service/InsuranceService.java
Labels: feature

#27 [Refactor] 상품 목록 조회 API 쿼리문 수정
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
Labels: refactor

#28 [Refactor] 상품 목록 조회 API response dto 수정
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
  src/main/java/xyz/iwasacar/api/domain/products/dto/response/ProductResponse.java
Labels: refactor

#26 [feat] 로그
  build.gradle
  src/main/java/xyz/iwasacar/api/common/aop/LogAspect.java
  src/main/java/xyz/iwasacar/api/common/config/FilterConfig.java
  src/main/java/xyz/iwasacar/api/common/context/UuidContext.java
  src/main/java/xyz/iwasacar/api/common/exception/advice/GlobalRestControllerAdvice.java
  src/main/java/xyz/iwasacar/api/common/filter/Utf8EncodingFilter.java
  src/main/java/xyz/iwasacar/api/common/filter/UuidContextFilter.java
  src/main/java/xyz/iwasacar/api/domain/logs/aop/LoginLogAspect.java
  src/main/java/xyz/iwasacar/api/domain/logs/controller/LogController.java
  src/main/java/xyz/iwasacar/api/domain/logs/dto/LogResponse.java
  src/main/java/xyz/iwasacar/api/domain/logs/entity/Log.java
  src/main/java/xyz/iwasacar/api/domain/logs/repository/LogRepository.java
  src/main/java/xyz/iwasacar/api/domain/logs/repository/LogRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/logs/repository/LogRepositoryCustomImpl.java
  src/main/java/xyz/iwasacar/api/domain/logs/service/DefaultLogService.java
  src/main/java/xyz/iwasacar/api/domain/logs/service/LogService.java
  src/main/java/xyz/iwasacar/api/domain/members/controller/MemberController.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/request/LoginRequest.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/MemberResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/entity/Member.java
  src/main/java/xyz/iwasacar/api/domain/members/exception/MemberNotFoundException.java
  src/main/java/xyz/iwasacar/api/domain/members/repository/MemberRepository.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
  src/main/resources/.gitkeep
  src/main/resources/logs/log4j-local.xml
  src/main/resources/logs/log4j2-dev.xml
  src/main/resources/logs/log4j2-prod.xml
Labels: feature, admin

#29 [feat] redis session
  build.gradle
Labels: feature

#30 [docs] swagger
  build.gradle
  src/main/java/xyz/iwasacar/api/common/config/SwaggerConfig.java
Labels: documentation

#31 refactor: 쿼리 수정 [#3]
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
  src/main/java/xyz/iwasacar/api/domain/products/controller/ProductController.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
Labels: refactor

#32 [release] 배포
  build.gradle
  src/main/java/xyz/iwasacar/api/common/aop/LogAspect.java
  src/main/java/xyz/iwasacar/api/common/config/FilterConfig.java
  src/main/java/xyz/iwasacar/api/common/config/P6spyLogMessageFormatConfiguration.java
  src/main/java/xyz/iwasacar/api/common/config/SwaggerConfig.java
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
  src/main/java/xyz/iwasacar/api/common/config/database/DataSourceConfig.java
  src/main/java/xyz/iwasacar/api/common/config/database/DataSourceType.java
  src/main/java/xyz/iwasacar/api/common/config/database/DbConstUtil.java
  src/main/java/xyz/iwasacar/api/common/config/database/RoutingDataSource.java
  src/main/java/xyz/iwasacar/api/common/config/database/RoutingDataSourceConfig.java
  src/main/java/xyz/iwasacar/api/common/context/UuidContext.java
  src/main/java/xyz/iwasacar/api/common/exception/advice/GlobalRestControllerAdvice.java
  src/main/java/xyz/iwasacar/api/common/filter/Utf8EncodingFilter.java
  src/main/java/xyz/iwasacar/api/common/filter/UuidContextFilter.java
  src/main/java/xyz/iwasacar/api/domain/brands/entity/Brand.java
  src/main/java/xyz/iwasacar/api/domain/common/constant/EntityStatus.java
  src/main/java/xyz/iwasacar/api/domain/consenthistories/entity/DocumentConsentHistory.java
  src/main/java/xyz/iwasacar/api/domain/insurances/controller/InsuranceController.java
  src/main/java/xyz/iwasacar/api/domain/insurances/dto/response/InsuranceResponse.java
  src/main/java/xyz/iwasacar/api/domain/insurances/repository/InsuranceRepository.java
  src/main/java/xyz/iwasacar/api/domain/insurances/service/DefaultInsuranceService.java
  src/main/java/xyz/iwasacar/api/domain/insurances/service/InsuranceService.java
  src/main/java/xyz/iwasacar/api/domain/labels/entity/LabelName.java
  src/main/java/xyz/iwasacar/api/domain/loans/controller/LoanController.java
  src/main/java/xyz/iwasacar/api/domain/loans/dto/response/LoanResponse.java
  src/main/java/xyz/iwasacar/api/domain/loans/entity/Loan.java
  src/main/java/xyz/iwasacar/api/domain/loans/repository/LoanRepository.java
  src/main/java/xyz/iwasacar/api/domain/loans/repository/LoanRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/loans/repository/LoanRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/loans/service/DefaultLoanService.java
  src/main/java/xyz/iwasacar/api/domain/loans/service/LoanService.java
  src/main/java/xyz/iwasacar/api/domain/logs/aop/LoginLogAspect.java
  src/main/java/xyz/iwasacar/api/domain/logs/controller/LogController.java
  src/main/java/xyz/iwasacar/api/domain/logs/dto/LogResponse.java
  src/main/java/xyz/iwasacar/api/domain/logs/entity/Log.java
  src/main/java/xyz/iwasacar/api/domain/logs/repository/LogRepository.java
  src/main/java/xyz/iwasacar/api/domain/logs/repository/LogRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/logs/repository/LogRepositoryCustomImpl.java
  src/main/java/xyz/iwasacar/api/domain/logs/service/DefaultLogService.java
  src/main/java/xyz/iwasacar/api/domain/logs/service/LogService.java
  src/main/java/xyz/iwasacar/api/domain/members/controller/MemberController.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/request/LoginRequest.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/MemberResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/entity/Member.java
  src/main/java/xyz/iwasacar/api/domain/members/exception/MemberNotFoundException.java
  src/main/java/xyz/iwasacar/api/domain/members/repository/MemberRepository.java
  src/main/java/xyz/iwasacar/api/domain/products/controller/ProductController.java
  src/main/java/xyz/iwasacar/api/domain/products/dto/response/ProductResponse.java
  src/main/java/xyz/iwasacar/api/domain/products/repository/ProductRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/products/service/DefaultProductService.java
  src/main/java/xyz/iwasacar/api/domain/products/service/ProductService.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
  src/main/resources/.gitkeep
  src/main/resources/logs/log4j2-dev.xml
  src/main/resources/logs/log4j2-local.xml
  src/main/resources/logs/log4j2-prod.xml
  src/test/resources/logs/log4j2-local.xml
Labels: relase

#33 [release] 배포
  build.gradle
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
  src/main/resources/logs/log4j2-dev.xml
  src/main/resources/logs/log4j2-local.xml
  src/test/resources/logs/log4j2-local.xml
Labels: relase

#34 [refactor] 프론트엔드test하면서 안되는 부분 수정
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
Labels: refactor

#35 [release] 수정 후 배포
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
Labels: relase

#36 test: 자원 조회 테스트
  build.gradle
  src/main/java/xyz/iwasacar/api/domain/brands/entity/Brand.java
  src/main/java/xyz/iwasacar/api/domain/brands/repository/BrandRepository.java
  src/main/java/xyz/iwasacar/api/domain/cartypes/entity/CarType.java
  src/main/java/xyz/iwasacar/api/domain/cartypes/repository/CarTypeRepository.java
  src/main/java/xyz/iwasacar/api/domain/colors/entity/Color.java
  src/main/java/xyz/iwasacar/api/domain/colors/repository/ColorRepository.java
  src/main/java/xyz/iwasacar/api/domain/labels/entity/Label.java
  src/main/java/xyz/iwasacar/api/domain/labels/repository/LabelRepository.java
  src/main/java/xyz/iwasacar/api/domain/products/entity/Product.java
  src/main/java/xyz/iwasacar/api/domain/products/repository/ProductImageRepository.java
  src/main/java/xyz/iwasacar/api/domain/resources/entity/ProductImage.java
  src/main/java/xyz/iwasacar/api/domain/resources/entity/Resource.java
  src/main/java/xyz/iwasacar/api/domain/roles/entity/Role.java
  src/main/java/xyz/iwasacar/api/domain/roles/repository/RoleRepository.java
  src/test/java/xyz/iwasacar/api/config/TestConfig.java
  src/test/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryTest.java
  src/test/java/xyz/iwasacar/api/dummy/Dummy.java
Labels: test

#37 [test] 상품 조회 testa 코드 개발
  src/main/java/xyz/iwasacar/api/domain/products/service/DefaultProductService.java
  src/main/java/xyz/iwasacar/api/domain/resources/entity/ProductImage.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
  src/test/java/xyz/iwasacar/api/domain/products/controller/ProductControllerTest.java
  src/test/java/xyz/iwasacar/api/domain/products/service/DefaultProductServiceTest.java
  src/test/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryTest.java
  src/test/java/xyz/iwasacar/api/dummy/Dummy.java
Labels: test

#38 [refactor] 인증 / 인가 리팩토링
  build.gradle
  src/main/java/xyz/iwasacar/api/common/annotation/Login.java
  src/main/java/xyz/iwasacar/api/common/argumentresolver/MemberClaimArgumentResolver.java
  src/main/java/xyz/iwasacar/api/common/auth/jwt/JwtDto.java
  src/main/java/xyz/iwasacar/api/common/auth/jwt/JwtTokenParser.java
  src/main/java/xyz/iwasacar/api/common/auth/jwt/JwtTokenProvider.java
  src/main/java/xyz/iwasacar/api/common/auth/jwt/JwtUtil.java
  src/main/java/xyz/iwasacar/api/common/auth/jwt/MemberClaim.java
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
  src/main/java/xyz/iwasacar/api/common/exception/base/ExceptionStatus.java
  src/main/java/xyz/iwasacar/api/common/interceptor/AdminInterceptor.java
  src/main/java/xyz/iwasacar/api/common/interceptor/BearerAuthInterceptor.java
  src/main/java/xyz/iwasacar/api/domain/members/controller/MemberController.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/MemberJwtResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/MemberResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/exception/ForbiddenException.java
  src/main/java/xyz/iwasacar/api/domain/members/service/MemberService.java
  src/main/java/xyz/iwasacar/api/domain/members/service/MemberServiceImpl.java
  src/main/java/xyz/iwasacar/api/domain/roles/exception/RoleNotFoundException.java
  src/main/java/xyz/iwasacar/api/domain/roles/repository/MemberRoleRepository.java
  src/main/java/xyz/iwasacar/api/domain/roles/repository/RoleRepository.java
  src/main/java/xyz/iwasacar/api/domain/roles/repository/RoleRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/roles/repository/RoleRepositoryImpl.java
  src/main/resources/logs/log4j2-dev.xml
  src/main/resources/logs/log4j2-local.xml
  src/main/resources/logs/log4j2-prod.xml
  src/test/java/xyz/iwasacar/api/common/auth/jwt/JwtTokenParserTest.java
Labels: feature, refactor

#41 [feat] 판매 API 구현
  src/main/java/xyz/iwasacar/api/common/component/AwsS3Uploader.java
  src/main/java/xyz/iwasacar/api/common/config/MultipartConfig.java
  src/main/java/xyz/iwasacar/api/common/exception/base/ExceptionStatus.java
  src/main/java/xyz/iwasacar/api/common/exception/base/FileConvertException.java
  src/main/java/xyz/iwasacar/api/domain/banks/exception/BankNotFoundException.java
  src/main/java/xyz/iwasacar/api/domain/banks/repository/BankRepository.java
  src/main/java/xyz/iwasacar/api/domain/brands/exception/BrandNotFoundException.java
  src/main/java/xyz/iwasacar/api/domain/caroptions/entity/CarOption.java
  src/main/java/xyz/iwasacar/api/domain/caroptions/exception/CarOptionException.java
  src/main/java/xyz/iwasacar/api/domain/caroptions/repository/CarOptionRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/caroptions/repository/CarOptionRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/caroptions/repository/ProductOptionRepository.java
  src/main/java/xyz/iwasacar/api/domain/cartypes/exception/CarTypeNotFoundException.java
  src/main/java/xyz/iwasacar/api/domain/colors/exception/ColorNotFoundException.java
  src/main/java/xyz/iwasacar/api/domain/histories/controller/SaleHistoryController.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/request/SaleRequest.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/SaleResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/entity/SaleHistory.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/SaleHistoryRepository.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/DefaultSaleService.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/SaleService.java
  src/main/java/xyz/iwasacar/api/domain/labels/entity/LabelName.java
  src/main/java/xyz/iwasacar/api/domain/labels/exception/LabelNotFoundException.java
  src/main/java/xyz/iwasacar/api/domain/labels/repository/LabelRepository.java
  src/main/java/xyz/iwasacar/api/domain/members/controller/MemberController.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/request/LoginRequest.java
  src/main/java/xyz/iwasacar/api/domain/members/service/MemberServiceImpl.java
  src/main/java/xyz/iwasacar/api/domain/products/entity/Product.java
  src/main/java/xyz/iwasacar/api/domain/products/exception/ProductNotFound.java
  src/main/java/xyz/iwasacar/api/domain/products/service/DefaultProductService.java
  src/main/java/xyz/iwasacar/api/domain/resources/entity/Resource.java
  src/main/java/xyz/iwasacar/api/domain/roles/repository/RoleRepository.java
  src/test/java/xyz/iwasacar/api/dummy/Dummy.java
Labels: feature

#39 [feat] 특정 상품 조회 API
  src/main/java/xyz/iwasacar/api/domain/products/controller/ProductController.java
  src/main/java/xyz/iwasacar/api/domain/products/service/DefaultProductService.java
  src/main/java/xyz/iwasacar/api/domain/products/service/ProductService.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
Labels: feature

#40 [feat] 구매 내역 저장 API
  src/main/java/xyz/iwasacar/api/common/aop/LogAspect.java
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
  src/main/java/xyz/iwasacar/api/common/exception/base/ExceptionStatus.java
  src/main/java/xyz/iwasacar/api/domain/banks/exception/BankNotFound.java
  src/main/java/xyz/iwasacar/api/domain/histories/controller/HistoryController.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/request/PurchaseHistoryRequest.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/PurchaseHistoryResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/entity/PurchaseHistory.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/PurchaseHistoryRepository.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/DefaultHistoryService.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/HistoryService.java
  src/main/java/xyz/iwasacar/api/domain/insurances/exception/InsuranceNotFound.java
  src/main/java/xyz/iwasacar/api/domain/loans/exception/LoanNotFound.java
  src/main/java/xyz/iwasacar/api/domain/products/entity/Product.java
  src/main/resources/logs/log4j2-prod.xml
Labels: feature

#42 [feat] 회원정보 전체, 상세 조회 API 작성
  src/main/java/xyz/iwasacar/api/common/annotation/Login.java
  src/main/java/xyz/iwasacar/api/common/argumentresolver/MemberClaimArgumentResolver.java
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
  src/main/java/xyz/iwasacar/api/common/context/MemberClaimContext.java
  src/main/java/xyz/iwasacar/api/common/exception/advice/GlobalRestControllerAdvice.java
  src/main/java/xyz/iwasacar/api/common/filter/UuidContextFilter.java
  src/main/java/xyz/iwasacar/api/common/interceptor/BearerAuthInterceptor.java
  src/main/java/xyz/iwasacar/api/domain/members/controller/MemberController.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/AllMemberResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/MemberDetailResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/repository/MemberRepository.java
  src/main/java/xyz/iwasacar/api/domain/members/repository/MemberRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/members/repository/MemberRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/members/service/MemberService.java
  src/main/java/xyz/iwasacar/api/domain/members/service/MemberServiceImpl.java
Labels: feature

#43 [refactor] 구매 내역 entity 수정 및 수정에 따른 로직 수정
  src/main/java/xyz/iwasacar/api/common/exception/base/ExceptionStatus.java
  src/main/java/xyz/iwasacar/api/domain/banks/exception/BankNotFound.java
  src/main/java/xyz/iwasacar/api/domain/histories/controller/HistoryController.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/request/PurchaseHistoryRequest.java
  src/main/java/xyz/iwasacar/api/domain/histories/entity/PurchaseHistory.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/DefaultPurchaseService.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/PurchaseService.java
  src/main/java/xyz/iwasacar/api/domain/insurances/exception/InsuranceNotFound.java
  src/main/java/xyz/iwasacar/api/domain/loans/exception/LoanNotFound.java
  src/main/java/xyz/iwasacar/api/domain/products/service/DefaultProductService.java
Labels: refactor
