Repository woorifisa-projects/i-was-a-car-back, pull requests merged in 2023-09, with the labels that each got.

#46 [feat] 구매 기록 조회 API 구현
  src/main/java/xyz/iwasacar/api/common/exception/base/ExceptionStatus.java
  src/main/java/xyz/iwasacar/api/domain/histories/controller/PurchaseHistoryController.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/PurchaseHistoryDetailResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/PurchaseResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/request/PurchaseHistoryRequest.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/PurchaseHistoryResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/entity/PurchaseHistory.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/PurchaseHistoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/PurchaseHistoryRepository.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/PurchaseHistoryRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/PurchaseHistoryService.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/PurchaseHistoryServiceImpl.java
Labels: feature

#48 [chore] CORS 수정 및 로그 형식 수정
  src/main/java/xyz/iwasacar/api/common/exception/advice/GlobalRestControllerAdvice.java
  src/main/resources/logs/log4j2-prod.xml
Labels: refactor

#52 [release] Sprint 3 오류 수정 - to develop
  src/main/java/xyz/iwasacar/api/common/exception/advice/GlobalRestControllerAdvice.java
  src/main/java/xyz/iwasacar/api/common/exception/base/ExceptionStatus.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/request/PurchaseHistoryRequest.java
  src/main/java/xyz/iwasacar/api/domain/histories/entity/PurchaseHistory.java
Labels: relase

#51 [release] Sprint 3 오류 수정 - to main
  src/main/java/xyz/iwasacar/api/common/exception/advice/GlobalRestControllerAdvice.java
  src/main/java/xyz/iwasacar/api/common/exception/base/ExceptionStatus.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/request/PurchaseHistoryRequest.java
  src/main/java/xyz/iwasacar/api/domain/histories/entity/PurchaseHistory.java
Labels: relase

#56 [refactor] sale api 연결
  build.gradle
  src/main/java/xyz/iwasacar/api/IWasACarApiServerApplication.java
  src/main/java/xyz/iwasacar/api/common/config/FeignClientBasicConfig.java
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
  src/main/java/xyz/iwasacar/api/common/exception/base/ServerException.java
  src/main/java/xyz/iwasacar/api/common/filter/UuidContextFilter.java
  src/main/java/xyz/iwasacar/api/domain/banks/BankController.java
  src/main/java/xyz/iwasacar/api/domain/banks/dto/response/BankResponse.java
  src/main/java/xyz/iwasacar/api/domain/banks/service/BankService.java
  src/main/java/xyz/iwasacar/api/domain/banks/service/DefaultBankService.java
  src/main/java/xyz/iwasacar/api/domain/histories/client/SaleClient.java
  src/main/java/xyz/iwasacar/api/domain/histories/controller/SaleHistoryController.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/request/SaleRequest.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/CarInfoResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/DefaultSaleService.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/SaleService.java
  src/main/java/xyz/iwasacar/api/domain/products/service/DefaultProductService.java
Labels: refactor

#54 [feat] 인증/인가 API 구현
  build.gradle
  src/main/java/xyz/iwasacar/api/common/auth/email/EmailMessage.java
  src/main/java/xyz/iwasacar/api/common/auth/email/EmailSession.java
  src/main/java/xyz/iwasacar/api/common/auth/email/controller/EmailController.java
  src/main/java/xyz/iwasacar/api/common/auth/email/dto/request/EmailConfirmRequest.java
  src/main/java/xyz/iwasacar/api/common/auth/email/dto/request/EmailRequest.java
  src/main/java/xyz/iwasacar/api/common/auth/email/dto/response/EmailResponse.java
  src/main/java/xyz/iwasacar/api/common/auth/email/exception/EmailCodeNotFoundException.java
  src/main/java/xyz/iwasacar/api/common/auth/email/exception/EmailServerException.java
  src/main/java/xyz/iwasacar/api/common/auth/email/exception/InvalidEmailVerificationException.java
  src/main/java/xyz/iwasacar/api/common/auth/email/service/EmailService.java
  src/main/java/xyz/iwasacar/api/common/auth/jwt/JwtTokenParser.java
  src/main/java/xyz/iwasacar/api/common/auth/jwt/JwtUtil.java
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
  src/main/java/xyz/iwasacar/api/common/exception/advice/GlobalRestControllerAdvice.java
  src/main/java/xyz/iwasacar/api/common/exception/base/ExceptionStatus.java
  src/main/java/xyz/iwasacar/api/domain/members/controller/MemberController.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/request/SignupRequest.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/request/UpdateRequest.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/MemberResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/MemberUpdateResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/entity/Member.java
  src/main/java/xyz/iwasacar/api/domain/members/service/MemberService.java
  src/main/java/xyz/iwasacar/api/domain/members/service/MemberServiceImpl.java
  src/main/resources/templates/email.html
Labels: feature

#53 [refactor] 문서 아이템 가져올때 상태가 delete인 거 제외
  src/main/java/xyz/iwasacar/api/domain/documentitems/repository/DocumentItemRepositoryImpl.java
Labels: refactor

#59 [feat] 검색 기능 추가
  src/main/java/xyz/iwasacar/api/domain/products/controller/ProductController.java
  src/main/java/xyz/iwasacar/api/domain/products/service/DefaultProductService.java
  src/main/java/xyz/iwasacar/api/domain/products/service/ProductService.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
Labels: feature

#60 [test] car type test 코드 작성
  src/main/java/xyz/iwasacar/api/domain/banks/controller/BankController.java
  src/main/java/xyz/iwasacar/api/domain/cartypes/controller/CarTypeController.java
  src/test/java/xyz/iwasacar/api/domain/cartypes/controller/CarTypeControllerTest.java
  src/test/java/xyz/iwasacar/api/domain/cartypes/repository/CarTypeRepositoryTest.java
  src/test/java/xyz/iwasacar/api/domain/cartypes/service/DefaultCarTypeServiceTest.java
  src/test/java/xyz/iwasacar/api/domain/products/controller/ProductControllerTest.java
  src/test/java/xyz/iwasacar/api/domain/products/service/DefaultProductServiceTest.java
  src/test/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryTest.java
Labels: test

#62 [test] loans 테스트 코드 작성
  src/main/java/xyz/iwasacar/api/domain/banks/entity/Bank.java
  src/test/java/xyz/iwasacar/api/domain/banks/controller/BankControllerTest.java
  src/test/java/xyz/iwasacar/api/domain/banks/repository/BankRepositoryTest.java
  src/test/java/xyz/iwasacar/api/domain/banks/service/DefaultBankServiceTest.java
  src/test/java/xyz/iwasacar/api/dummy/Dummy.java
Labels: test

#55 [feat][refactor] 판매 내역 전체, 상세 조회 구현 + 기존 코드 합치기
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
  src/main/java/xyz/iwasacar/api/domain/histories/controller/PurchaseHistoryController.java
  src/main/java/xyz/iwasacar/api/domain/histories/controller/SaleHistoryController.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/PurchaseHistoryDetailResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/PurchaseHistoryResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/PurchaseResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/SaleHistoryDetailResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/SaleHistoryResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/PurchaseHistoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/PurchaseHistoryRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/SaleHistoryRepository.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/SaleHistoryRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/SaleHistoryRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/DefaultSaleService.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/PurchaseHistoryService.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/PurchaseHistoryServiceImpl.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/SaleService.java
  src/main/java/xyz/iwasacar/api/domain/members/controller/MemberController.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/MemberDetailResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/MemberResponse.java
Labels: feature, refactor

#57 [feature] 관리자 사용자 관리
  src/main/java/xyz/iwasacar/api/domain/members/controller/admin/AdminMemberController.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/request/MemberUpdateRequest.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/AdminMemberUpdateResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/entity/Member.java
  src/main/java/xyz/iwasacar/api/domain/members/repository/MemberRepository.java
  src/main/java/xyz/iwasacar/api/domain/members/service/MemberService.java
  src/main/java/xyz/iwasacar/api/domain/members/service/MemberServiceImpl.java
Labels: feature, admin

#58 [feat] 관리자 상품 관리
  src/main/java/xyz/iwasacar/api/common/component/AwsS3Uploader.java
  src/main/java/xyz/iwasacar/api/common/config/MultipartConfig.java
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
  src/main/java/xyz/iwasacar/api/common/dto/response/CommonResponse.java
  src/main/java/xyz/iwasacar/api/common/dto/response/PageResponse.java
  src/main/java/xyz/iwasacar/api/domain/caroptions/repository/CarOptionRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/caroptions/repository/CarOptionRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/histories/controller/SaleHistoryController.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/request/ProductCreateRequest.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/CarInfoResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/SaleResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/DefaultSaleService.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/SaleService.java
  src/main/java/xyz/iwasacar/api/domain/products/controller/ProductController.java
  src/main/java/xyz/iwasacar/api/domain/products/controller/admin/AdminProductController.java
  src/main/java/xyz/iwasacar/api/domain/products/dto/response/ProductDetailResponse.java
  src/main/java/xyz/iwasacar/api/domain/products/dto/response/ProductResponse.java
  src/main/java/xyz/iwasacar/api/domain/products/entity/Product.java
  src/main/java/xyz/iwasacar/api/domain/products/repository/ProductRepository.java
  src/main/java/xyz/iwasacar/api/domain/products/repository/ProductRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/products/repository/ProductRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/products/service/AdminProductService.java
  src/main/java/xyz/iwasacar/api/domain/products/service/DefaultProductService.java
  src/main/java/xyz/iwasacar/api/domain/products/service/ProductService.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
  src/test/java/xyz/iwasacar/api/dummy/Dummy.java
Labels: feature, admin

#63 [refactor] 전체 멤버 조회 반환값 수정
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/AllMemberResponse.java
Labels: refactor

#64 [refactor] 로그 dto 반환 값 변경
  src/main/java/xyz/iwasacar/api/domain/logs/dto/LogResponse.java
  src/main/java/xyz/iwasacar/api/domain/logs/entity/Log.java
  src/main/java/xyz/iwasacar/api/domain/logs/repository/LogRepositoryCustomImpl.java
Labels: refactor

#65 [Hotfix] 예외 처리 및 로그 추가
  src/main/java/xyz/iwasacar/api/common/dto/response/ErrorResponse.java
  src/main/java/xyz/iwasacar/api/common/exception/advice/GlobalRestControllerAdvice.java
  src/main/java/xyz/iwasacar/api/domain/histories/controller/HistoryController.java
  src/main/java/xyz/iwasacar/api/domain/logs/aop/HistoryAspect.java
  src/main/java/xyz/iwasacar/api/domain/logs/aop/LoginLogAspect.java
  src/main/java/xyz/iwasacar/api/domain/logs/entity/Log.java
Labels: bug

#67 [refactor] ACCESS_TOKEN 외 커스텀 쿠키 인터셉터 false 반환
  src/main/java/xyz/iwasacar/api/common/interceptor/BearerAuthInterceptor.java
Labels: refactor

#68 [fix] : 로그인 안되는 에러 해결
  src/main/java/xyz/iwasacar/api/domain/logs/aop/LoginLogAspect.java
Labels: bug

#69 [fix] 인터셉터 제외 경로 수정
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
Labels: refactor

#72 [feat] : 관리자 상품 상세페이지 수정 [#6]
  src/main/java/xyz/iwasacar/api/common/exception/base/ExceptionStatus.java
  src/main/java/xyz/iwasacar/api/common/interceptor/AdminInterceptor.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/HistoryAdminResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/entity/SaleHistory.java
  src/main/java/xyz/iwasacar/api/domain/histories/exception/SaleHistoryNotFoundException.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/SaleHistoryRepository.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/SaleHistoryRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/SaleHistoryRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/DefaultSaleService.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/SaleService.java
  src/main/java/xyz/iwasacar/api/domain/products/controller/admin/AdminProductController.java
  src/main/java/xyz/iwasacar/api/domain/products/dto/response/ProductSaleDetailResponse.java
  src/main/java/xyz/iwasacar/api/domain/products/service/AdminProductService.java
  src/main/java/xyz/iwasacar/api/domain/products/service/DefaultProductService.java
  src/main/java/xyz/iwasacar/api/domain/products/service/ProductService.java
Labels: feature

#73 [hotfix] : 관리자 페이지 수정사항 (심사대기 차량 조회)
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
  src/main/java/xyz/iwasacar/api/domain/members/repository/MemberRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/products/controller/admin/AdminProductController.java
  src/main/java/xyz/iwasacar/api/domain/products/repository/ProductRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/products/repository/ProductRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/products/service/AdminProductService.java
  src/main/java/xyz/iwasacar/api/domain/products/service/DefaultProductService.java
  src/main/java/xyz/iwasacar/api/domain/products/service/ProductService.java
Labels: bug

#75 [fix] 페이지 size value 변경
  src/main/java/xyz/iwasacar/api/domain/histories/controller/PurchaseHistoryController.java
  src/main/java/xyz/iwasacar/api/domain/histories/controller/SaleHistoryController.java
  src/main/java/xyz/iwasacar/api/domain/logs/controller/LogController.java
  src/main/java/xyz/iwasacar/api/domain/members/controller/MemberController.java
  src/main/java/xyz/iwasacar/api/domain/products/controller/admin/AdminProductController.java
Labels: bug

#76 [feat] 회원 정보 조회
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
  src/main/java/xyz/iwasacar/api/common/interceptor/AdminInterceptor.java
  src/main/java/xyz/iwasacar/api/domain/members/client/MemberClient.java
  src/main/java/xyz/iwasacar/api/domain/members/controller/MemberController.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/MemberJwtResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/MemberResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/service/MemberService.java
  src/main/java/xyz/iwasacar/api/domain/members/service/MemberServiceImpl.java
Labels: feature

#77 [feat] 관리자 파일 등록
  src/main/java/xyz/iwasacar/api/domain/labels/LabelController.java
  src/main/java/xyz/iwasacar/api/domain/labels/dto/response/LabelResponse.java
  src/main/java/xyz/iwasacar/api/domain/labels/repository/LabelRepository.java
  src/main/java/xyz/iwasacar/api/domain/labels/service/DefaultLabelService.java
  src/main/java/xyz/iwasacar/api/domain/labels/service/LabelService.java
  src/main/java/xyz/iwasacar/api/domain/members/client/MemberClient.java
  src/main/java/xyz/iwasacar/api/domain/members/controller/MemberController.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/MemberResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/service/MemberService.java
  src/main/java/xyz/iwasacar/api/domain/members/service/MemberServiceImpl.java
  src/main/java/xyz/iwasacar/api/domain/products/controller/admin/AdminProductController.java
  src/main/java/xyz/iwasacar/api/domain/products/dto/reqeust/AdminProductUpdateRequest.java
  src/main/java/xyz/iwasacar/api/domain/products/dto/response/AdminProductUpdateResponse.java
  src/main/java/xyz/iwasacar/api/domain/products/entity/Product.java
  src/main/java/xyz/iwasacar/api/domain/products/service/AdminProductService.java
  src/main/java/xyz/iwasacar/api/domain/products/service/DefaultProductService.java
  src/main/java/xyz/iwasacar/api/domain/products/service/ProductService.java
  src/main/java/xyz/iwasacar/api/domain/roles/repository/MemberRoleRepository.java
  src/main/java/xyz/iwasacar/api/domain/roles/repository/MemberRoleRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/roles/repository/MemberRoleRepositoryImpl.java
Labels: feature, admin

#78 [hotfix] 라벨네임 추가
  src/main/java/xyz/iwasacar/api/domain/labels/entity/LabelName.java
Labels: bug

#79 [hotfix] 성능 기록부 추가 오류 수정
  src/main/java/xyz/iwasacar/api/domain/products/service/AdminProductService.java
Labels: bug

#80 [feat] 문서 동의 API
  src/main/java/xyz/iwasacar/api/domain/consenthistories/entity/DocumentConsentHistory.java
  src/main/java/xyz/iwasacar/api/domain/documentitems/controller/DocumentItemController.java
  src/main/java/xyz/iwasacar/api/domain/documentitems/dto/request/DocumentConsentRequest.java
  src/main/java/xyz/iwasacar/api/domain/documentitems/dto/response/DocumentItemResponse.java
  src/main/java/xyz/iwasacar/api/domain/documentitems/repository/DocumentConsentHistoryRepository.java
  src/main/java/xyz/iwasacar/api/domain/documentitems/repository/DocumentItemRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/documentitems/repository/DocumentItemRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/documentitems/service/DefaultDocumentItemService.java
  src/main/java/xyz/iwasacar/api/domain/documentitems/service/DocumentItemService.java
  src/main/java/xyz/iwasacar/api/domain/documents/repository/DocumentRepository.java
  src/main/java/xyz/iwasacar/api/domain/members/client/MemberClient.java
  src/main/java/xyz/iwasacar/api/domain/products/controller/admin/AdminProductController.java
Labels: feature

#71 refactore: 판매 API 수정 [#3]
  src/main/java/xyz/iwasacar/api/common/aop/LogAspect.java
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
  src/main/java/xyz/iwasacar/api/common/interceptor/AdminInterceptor.java
Labels: refactor

#70 [refactor] 구매 관련 로직 연결하면서 수정 사항 발생
  src/main/java/xyz/iwasacar/api/domain/labels/entity/LabelName.java
  src/main/java/xyz/iwasacar/api/domain/loans/dto/response/LoanResponse.java
  src/main/java/xyz/iwasacar/api/domain/logs/dto/LogResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/controller/admin/AdminMemberController.java
  src/main/java/xyz/iwasacar/api/domain/members/repository/MemberRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/products/dto/response/ProductResponse.java
Labels: refactor

#82 release to develop
  src/main/java/xyz/iwasacar/api/common/aop/LogAspect.java
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
  src/main/java/xyz/iwasacar/api/common/dto/response/CommonResponse.java
  src/main/java/xyz/iwasacar/api/domain/consenthistories/service/DefaultConsentHistoryService.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/PurchaseHistoryDetailResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/PurchaseResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/request/SaleRequest.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/DefaultSaleService.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
Labels: relase

#83 [feat] CORS Preflight 시 발생하는 오류 해결
  src/main/java/xyz/iwasacar/api/common/interceptor/AdminInterceptor.java
  src/main/java/xyz/iwasacar/api/common/interceptor/BearerAuthInterceptor.java
Labels: bug

#84 [hotfix]관리자 상품 전체 조회/ 심사 대기 중 차량 전체 조회
  src/main/java/xyz/iwasacar/api/domain/labels/entity/LabelName.java
  src/main/java/xyz/iwasacar/api/domain/products/repository/ProductRepositoryImpl.java
Labels: bug

#85 [fix] 인터셉터 제외 경로 수정(로그아웃)
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
Labels: refactor

#86 [fix] 인터셉터 제외 경로 수정(로그아웃)
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
Labels: refactor

#87 [fix] 인터셉터 제외 경로 수정(상품상세)
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
Labels: refactor

#88 [Test] 판매 테스트 코드 작성
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
  src/main/java/xyz/iwasacar/api/domain/banks/repository/BankRepository.java
  src/main/java/xyz/iwasacar/api/domain/brands/repository/BrandRepository.java
  src/main/java/xyz/iwasacar/api/domain/cartypes/repository/CarTypeRepository.java
  src/main/java/xyz/iwasacar/api/domain/colors/repository/ColorRepository.java
  src/main/java/xyz/iwasacar/api/domain/histories/controller/HistoryController.java
  src/main/java/xyz/iwasacar/api/domain/histories/controller/SaleHistoryController.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/request/ProductCreateRequest.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/request/PurchaseHistoryRequest.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/HistoryAdminResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/PurchaseHistoryResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/SaleHistoryDetailResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/SaleHistoryResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/SaleHistoryRepository.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/SaleHistoryRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/SaleHistoryRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/DefaultSaleService.java
  src/test/java/xyz/iwasacar/api/config/JwtTestConfig.java
  src/test/java/xyz/iwasacar/api/config/QueryDslTestConfig.java
  src/test/java/xyz/iwasacar/api/domain/banks/repository/BankRepositoryTest.java
  src/test/java/xyz/iwasacar/api/domain/cartypes/repository/CarTypeRepositoryTest.java
  src/test/java/xyz/iwasacar/api/domain/histories/controller/HistoryControllerTest.java
  src/test/java/xyz/iwasacar/api/domain/histories/controller/SaleHistoryControllerTest.java
  src/test/java/xyz/iwasacar/api/domain/histories/service/DefaultSaleServiceTest.java
  src/test/java/xyz/iwasacar/api/domain/insurances/repository/InsuranceRepositoryTest.java
  src/test/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryTest.java
  src/test/java/xyz/iwasacar/api/dummy/DtoDummy.java
  src/test/resources/images/sonata1.jpeg
  src/test/resources/images/sonata2.jpeg
  src/test/resources/images/sonata3.jpeg
Labels: test

#89 [fix] 심사대기 상품 상세 조회 시 발생 오류 해결
  src/main/java/xyz/iwasacar/api/common/filter/UuidContextFilter.java
  src/main/java/xyz/iwasacar/api/domain/common/constant/EntityStatus.java
  src/main/java/xyz/iwasacar/api/domain/histories/entity/SaleHistory.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/SaleHistoryRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/members/entity/Member.java
  src/main/java/xyz/iwasacar/api/domain/products/dto/response/ProductDetailResponse.java
  src/main/java/xyz/iwasacar/api/domain/products/dto/response/ProductSaleDetailResponse.java
  src/main/java/xyz/iwasacar/api/domain/products/service/AdminProductService.java
Labels: bug

#90 Hotfix url length
  src/main/java/xyz/iwasacar/api/common/component/AwsS3Uploader.java
Labels: bug

#93 [hotfix] 조건 중복 수정
  src/main/java/xyz/iwasacar/api/common/interceptor/BearerAuthInterceptor.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
Labels: bug

#92 [Test] member
  src/main/java/xyz/iwasacar/api/domain/members/controller/MemberController.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/request/LoginRequest.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/MemberDetailResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/MemberJwtResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/MemberUpdateResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/entity/Member.java
  src/main/java/xyz/iwasacar/api/domain/members/service/MemberServiceImpl.java
  src/test/java/xyz/iwasacar/api/domain/histories/controller/SaleHistoryControllerTest.java
  src/test/java/xyz/iwasacar/api/domain/members/controller/MemberControllerTest.java
  src/test/java/xyz/iwasacar/api/dummy/DtoDummy.java
  src/test/java/xyz/iwasacar/api/dummy/RequestUtil.java
Labels: test

#95 [hotfix] 라벨 이넘 수정
  src/main/java/xyz/iwasacar/api/domain/labels/entity/LabelName.java
Labels: bug

#94 [Hotfix] 쿼리 수정해서 빌드 오류 해결
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
Labels: refactor

#96 [hotfix] 파일명 -> UUID로 AWS에 저장
  src/main/java/xyz/iwasacar/api/common/component/AwsS3Uploader.java
  src/main/java/xyz/iwasacar/api/domain/members/controller/MemberController.java
Labels: bug

#97 [Release] Sprint-5-1 to main
  src/main/java/xyz/iwasacar/api/common/component/AwsS3Uploader.java
  src/main/java/xyz/iwasacar/api/common/config/WebMvcConfig.java
  src/main/java/xyz/iwasacar/api/common/filter/UuidContextFilter.java
  src/main/java/xyz/iwasacar/api/common/interceptor/AdminInterceptor.java
  src/main/java/xyz/iwasacar/api/common/interceptor/BearerAuthInterceptor.java
  src/main/java/xyz/iwasacar/api/domain/banks/repository/BankRepository.java
  src/main/java/xyz/iwasacar/api/domain/brands/repository/BrandRepository.java
  src/main/java/xyz/iwasacar/api/domain/cartypes/repository/CarTypeRepository.java
  src/main/java/xyz/iwasacar/api/domain/colors/repository/ColorRepository.java
  src/main/java/xyz/iwasacar/api/domain/histories/controller/HistoryController.java
  src/main/java/xyz/iwasacar/api/domain/histories/controller/SaleHistoryController.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/request/ProductCreateRequest.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/request/PurchaseHistoryRequest.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/HistoryAdminResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/PurchaseHistoryResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/SaleHistoryDetailResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/dto/response/SaleHistoryResponse.java
  src/main/java/xyz/iwasacar/api/domain/histories/entity/SaleHistory.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/SaleHistoryRepository.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/SaleHistoryRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/histories/repository/SaleHistoryRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/DefaultSaleService.java
  src/main/java/xyz/iwasacar/api/domain/histories/service/SaleService.java
  src/main/java/xyz/iwasacar/api/domain/labels/entity/LabelName.java
  src/main/java/xyz/iwasacar/api/domain/members/controller/MemberController.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/request/LoginRequest.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/MemberDetailResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/MemberJwtResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/dto/response/MemberUpdateResponse.java
  src/main/java/xyz/iwasacar/api/domain/members/entity/Member.java
  src/main/java/xyz/iwasacar/api/domain/members/repository/MemberRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/members/service/MemberServiceImpl.java
  src/main/java/xyz/iwasacar/api/domain/products/dto/response/ProductDetailResponse.java
  src/main/java/xyz/iwasacar/api/domain/products/dto/response/ProductResponse.java
  src/main/java/xyz/iwasacar/api/domain/products/dto/response/ProductSaleDetailResponse.java
  src/main/java/xyz/iwasacar/api/domain/products/repository/ProductRepositoryImpl.java
  src/main/java/xyz/iwasacar/api/domain/products/service/AdminProductService.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
  src/test/java/xyz/iwasacar/api/config/JwtTestConfig.java
  src/test/java/xyz/iwasacar/api/config/QueryDslTestConfig.java
  src/test/java/xyz/iwasacar/api/domain/banks/repository/BankRepositoryTest.java
  src/test/java/xyz/iwasacar/api/domain/cartypes/repository/CarTypeRepositoryTest.java
  src/test/java/xyz/iwasacar/api/domain/histories/controller/HistoryControllerTest.java
  src/test/java/xyz/iwasacar/api/domain/histories/controller/SaleHistoryControllerTest.java
  src/test/java/xyz/iwasacar/api/domain/histories/service/DefaultSaleServiceTest.java
  src/test/java/xyz/iwasacar/api/domain/insurances/repository/InsuranceRepositoryTest.java
  src/test/java/xyz/iwasacar/api/domain/members/controller/MemberControllerTest.java
  src/test/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryTest.java
  src/test/java/xyz/iwasacar/api/dummy/DtoDummy.java
  src/test/java/xyz/iwasacar/api/dummy/RequestUtil.java
  src/test/resources/images/sonata1.jpeg
  src/test/resources/images/sonata2.jpeg
  src/test/resources/images/sonata3.jpeg
Labels: relase

#99 docs: README.md
  README.md
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
Labels: documentation

#101 [bug] 상품 API 오류 수정
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
Labels: bug

#102 fix : 관리자페이지 상세, 전체 조회 API 수정
  src/main/java/xyz/iwasacar/api/domain/products/service/AdminProductService.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
Labels: bug

#103 [hotfix] admin controller 수정
  src/main/java/xyz/iwasacar/api/common/interceptor/AdminInterceptor.java
  src/main/java/xyz/iwasacar/api/domain/logs/controller/LogController.java
Labels: bug

#104 release to main
  src/main/java/xyz/iwasacar/api/common/interceptor/AdminInterceptor.java
  src/main/java/xyz/iwasacar/api/domain/logs/controller/LogController.java
  src/main/java/xyz/iwasacar/api/domain/products/service/AdminProductService.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryCustom.java
  src/main/java/xyz/iwasacar/api/domain/resources/repository/ResourceRepositoryImpl.java
Labels: bug, relase
